version: 2

seeds:
  - name: seed_atp_rankings_current
    description: A table with the current ATP rankings
    columns:
      - name: ranking_date
        tests:
          - not_null
      - name: rank
        tests:
          - not_null
      - name: player
        tests:
          - not_null
      - name: points
        tests:
          - not_null